'use strict';
var initialXlatTables = {
    'en': {
        'CONTACTS': 'Contacts',
        'ORDERS' : 'Orders',
        'USERS' : 'Users',
        'ADD_GOODS' : 'Add goods',
        'YOUR_ROLE' : 'your role is',
        'LOG_IN' : 'Log in',
        'LOGIN' : 'Login',
        'LOGOUT' : 'Log out',
        'ABOUT' : 'About',
        'HELP' : 'Help',
        'UNABLE_LOGIN' : 'Unable to log in.',
        'WRONG_PASS' : 'Please check that you have entered your login and password correctly.',
        'WRONG_PASS_CAPS' : 'Is the Caps Lock safely turned off?',
        'WRONG_PASS_LANG' : 'Maybe you are using the wrong input language? (e.g. German vs. English)',
        'WRONG_PASS_EDITOR' : 'Try typing your password in a text editor and pasting it into the "Password" field.',
        'PASSWORD' : 'Password',
        'REMEMBER_ME' : 'remember me',
        'NOT_REG_YET' : 'Not registered yet?',
        'SIGN_UP' : 'Sign up!',
        'NAME' : 'Name',
        'SURNAME' : 'Surname',
        'FATHERNAME' : 'Fathername',
        'BIRTHDAY' : 'Birthday',
        'TOWN' : 'Town',
        'STREET' : 'Street',
        'FLAT' : 'Flat',
        'HOUSE' : 'House',
        'COUNTRY' : 'Country',
        'EMAIL' : 'Email',
        'ENGLISH' : 'English',
        'RUSSIAN' : 'Русский'
    },
    'ru': {
        'CONTACTS': 'Контакты',
        'ORDERS' : 'Заказы',
        'USERS' : 'Пользователи',
        'ADD_GOODS' : 'Добавить товар',
        'YOUR_ROLE' : 'Ваша роль',
        'LOG_IN' : 'Войти',
        'LOGIN' : 'Логин',
        'LOGOUT' : 'Выйти',
        'ABOUT' : 'О сайте',
        'HELP' : 'Справка',
        'UNABLE_LOGIN' : 'Unable to log in.',
        'WRONG_PASS' : 'Please check that you have entered your login and password correctly.',
        'WRONG_PASS_CAPS' : 'Is the Caps Lock safely turned off?',
        'WRONG_PASS_LANG' : 'Maybe you are using the wrong input language? (e.g. German vs. English)',
        'WRONG_PASS_EDITOR' : 'Try typing your password in a text editor and pasting it into the "Password" field.',
        'PASSWORD' : 'Password',
        'REMEMBER_ME' : 'remember me',
        'NOT_REG_YET' : 'Not registered yet?',
        'SIGN_UP' : 'Sign up!',
        'NAME' : 'Name',
        'SURNAME' : 'Surname',
        'FATHERNAME' : 'Fathername',
        'BIRTHDAY' : 'Birthday',
        'TOWN' : 'Town',
        'STREET' : 'Street',
        'FLAT' : 'Flat',
        'HOUSE' : 'House',
        'COUNTRY' : 'Country',
        'EMAIL' : 'Email',
        'ENGLISH' : 'English',
        'RUSSIAN' : 'Русский'
    }
};
