Dear $NAME$,

Congratulations on the/your “…type in the event or happening…”. 
I know that you are very deserving of …”benefit of the change/event…”, and it pleases me to know that you have achieved this.

I regret not being able to congratulate you in person for this, but will hope to be in contact or see you sometime soon. 
Again congratulations, 
I’m sure that you’re both relieved and pleased, as you sure should be.

Wishing you the best,

$US_FULL_NAME$